version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - ../.env
    networks:
      - global-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5

  postgres:
    hostname: postgres
    container_name: postgres
    build:
      context: ./cutom-docker/postgres-multiple-databases/
      dockerfile: dockerfile
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - global-network

  postgres_admin:
    image: dpage/pgadmin4
    env_file:
      - ../.env
    depends_on:
      - postgres
    ports:
      - '15432:80'
    networks:
      - global-network

  mongodb:
    build:
      context: ./cutom-docker/monogodb-multiple-databases/
      dockerfile: Dockerfile
    container_name: mongodb
    restart: unless-stopped
    volumes:
      - ferwmongodb-dataaaqw:/data/db
    ports:
      - "27017:27017"
    networks:
      - global-network
    env_file:
      - ../.env

  mongo-express:
    image: mongo-express
    restart: always
    networks:
      - global-network
    ports:
      - 8081:8081
    env_file:
      - ../.env


  redis:
    image: redis:latest
    restart: always
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    ports:
      - "6379:6379"
    volumes:
      - redis-database:/root/redis
    env_file:
      - ../.env



volumes:
  postgres-data:
  ferwmongodb-dataaaqw:
  redis-database:


networks:
  global-network:
    driver: bridge
    name: intelli-network
